    #pragma once
// LOCAL VERBOSITY FOR EACH FUNTIONM  ////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// NB NEED TO INCLUDE CLASSNAME. TO PREVENT FUNCTION NAME CLASHES BETWEEN CLASSES..... OR MAKE IT ONE LIST PER CLASS.
// NB ALSO OVERLARDED FUNCTION NAMES WITHIN A CLASS.
	#define	V_VERBOSITY   1  // -1= NONE   0=ERRORS ONLY   1=BASIC   2=LOTS.

    // UTILS/ ###############################################################
    /////////////////////////////////////// CONVERTAHANDAPOVRAYTOSTANDARD.CPP
	#define	V_CONVERTAHANDAPOVRAYTOSTANDARD  2
	#define	V_LOADDEPTHAHANDA  2

	/////////////////////////////////////// CONF_PARAMS.CPP
	#define	V_CONF_PARAMS_CONF_PARAMS  1
	// #define	V_CONF_PARAMS_READ_VERBOSITY  1
	// #define	V_CONF_PARAMS_READ_PATHS  1
	// #define	V_CONF_PARAMS_READ_JPARAMS  1
	// #define	V_CONF_PARAMS_READVECVECFLOAT  1
	// #define	V_CONF_PARAMS_READVECFLOAT  1
	// #define	V_CONF_PARAMS_READVECSTRING  1
	#define	V_CONF_PARAMS_DISPLAY_PARAMS  1

	/////////////////////////////////////// PRINT_FUNCTIONS.CPP
	#define	V_PRINT_MATX33F  1
	#define	V_PRINT_MATX44F  1
	#define	V_PRINT_MATX61F  1
	#define	V_PRINT_FLOAT_6  1
	#define	V_PRINT_FLOAT_9  1
	#define	V_PRINT_FLOAT_16  1
	#define	V_PRINT_JSON_FLOAT_9  1
	#define	V_PRINT_MATF  1

    // DYNAIC_SLAM/ ##############################################
    /////////////////////////////////////// DYNAMIC_SLAM_CLASS.CPP
	#define	V__DYNAMIC_SLAM  0
	#define	V_DYNAMIC_SLAM_DYNAMIC_SLAM  0
	#define	V_DYNAMIC_SLAM_INITIALIZE_RESULTSMAT  0
	#define	V_DYNAMIC_SLAM_INITIALIZE_CAMERA  0
	#define	V_DYNAMIC_SLAM_NEXTFRAME   -2
	#define	V_DYNAMIC_SLAM_GETFRAME   0
	#define	V_DYNAMIC_SLAM_GETPOSE   0
	#define	V_DYNAMIC_SLAM_GETINVPOSE   0
	#define	V_DYNAMIC_SLAM_GETFRAMEDATA   0
	#define	V_DYNAMIC_SLAM_USE_GT_POSE   0
    ////
	#define	V_DYNAMIC_SLAM_ESTIMATECALIBRATION   0
	#define	V_DYNAMIC_SLAM_SPATIALCOSTFNS   0
	#define	V_DYNAMIC_SLAM_PARSIMONYCOSTFNS   0
	#define	V_DYNAMIC_SLAM_EXHAUSTIVESEARCH   0
	#define	V_DYNAMIC_SLAM_GETRESULT   0

    /////////////////////////////////////// DYNAMIC_SLAM_KEYFRAME.CPP
	#define	V_DYNAMIC_SLAM_INITIALIZE_KEYFRAME  -2
	//#define	V_DYNAMIC_SLAM_INITIALIZE_KEYFRAME_FROM_GT   -2
	//#define	V_DYNAMIC_SLAM_INITIALIZE_KEYFRAME_FROM_TRACKING   -2
	//#define	V_DYNAMIC_SLAM_INITIALIZE_NEW_KEYFRAME   -2

    /////////////////////////////////////// DYNAMIC_SLAM_MAPPING.CPP
	#define	V_DYNAMIC_SLAM_OPTIMIZE_DEPTH   0
	#define	V_DYNAMIC_SLAM_UPDATEDEPTHCOSTVOL   -2
	#define	V_DYNAMIC_SLAM_BUILDDEPTHCOSTVOL_FAST_PERIPHERAL   0
	#define	V_DYNAMIC_SLAM_UPDATEQD   -1
	#define	V_DYNAMIC_SLAM_CACHEGVALUES   -1
	#define	V_DYNAMIC_SLAM_UPDATEA   -1

    /////////////////////////////////////// DYNAMIC_SLAM_TRACKING.CPP
	#define	V_DYNAMIC_SLAM_REPORT_GT_POSE_ERROR   -2
	//#define	V_DYNAMIC_SLAM_DISPLAY_FRAME_RESLUTS   -2
	#define	V_DYNAMIC_SLAM_ARTIFICIAL_POSE_ERROR   -1
	#define	V_DYNAMIC_SLAM_PREDICTFRAME   -1
	#define	V_DYNAMIC_SLAM_GENERATE_INVK_   0
	#define	V_DYNAMIC_SLAM_GENERATE_SE3_K2K   0
	#define	V_DYNAMIC_SLAM_UPDATE_K2K   -2

	//#define	V_DYNAMIC_SLAM_UPDATE_K2K_4   -2
	#define	V_DYNAMIC_SLAM_COMPUTE_OPTIMUM   -2
	#define	V_DYNAMIC_SLAM_ESTIMATESE3   -2
	//#define	V_DYNAMIC_SLAM_ESTIMATESE3_LK   -2

	// RUNCL/ ##############################################
	/////////////////////////////////////// RUNCL_CLASS.CPP
	#define	V_RUNCL_RUNCL   0
	#define	V_RUNCL_TESTOPENCL   0
	#define	V_RUNCL_GETDEVICEINFOOPENCL   0
	#define	V_RUNCL_CREATEQUEUES   0
	#define	V_RUNCL_CREATEANDBULIDPROGRAMFROMSOURCE   0
	#define	V_RUNCL_CREATEKERNELS   0

	#define	V_RUNCL_CONVERTTOSTRING   0
	#define	V_RUNCL_INITIALIZE_FP32_PARAMS   0
	#define	V_RUNCL_INITIALIZE_RUNCL   0

	#define	V_RUNCL_MIPMAP_CALL_KERNEL   0
	#define	V_RUNCL_WAITFOREVENTANDRELEASE   0
	#define	V_RUNCL_ALLOCATEMEM   0

	#define	V__RUNCL   0
	#define	V_EXIT_   0

	/////////////////////////////////////// RUNCL_MACRO_CONVERSION.CPP
	//#define	V_CHECKERROR   1
	//#define	V_CHECKCVTYPE   1

	/////////////////////////////////////// RUNCL_DOWNLOADANDSAVE.CPP
	#define	V_RUNCL_CREATEFOLDERS   1
	#define	V_RUNCL_READOUTPUT   1
	#define	V_RUNCL_SAVECOSTVOLS   1
	#define	V_RUNCL_STORE_KEYFRAME   1
	#define	V_RUNCL_SAVE_VTK   1

	#define	V_RUNCL_DOWNLOADANDSAVE   -1
	#define	V_RUNCL_DOWNLOADANDSAVE_2CHANNEL_VOLUME   1

	#define	V_RUNCL_DOWNLOADANDSAVE_3CHANNEL   1
	#define	V_RUNCL_DOWNLOADANDSAVE_3CHANNEL_VOLUME   1

	#define	V_RUNCL_PREPARERESULTS_3CHANNEL  1
	#define	V_RUNCL_PREPARERESULTS_3CHANNEL_VOLUME  2


	#define	V_RUNCL_DOWNLOADANDSAVE_6CHANNEL   1
	#define	V_RUNCL_WRITETORESULTSMAT   1


	#define	V_RUNCL_DOWNLOADANDSAVE_HSV_GRAD   1
	#define	V_RUNCL_SAVEMAT   1
	#define	V_RUNCL_SAVEMAT_1CHAN   1

	#define	V_RUNCL_DOWNLOADANDSAVE_6CHANNEL_VOLUME   1

	#define	V_RUNCL_DOWNLOADANDSAVE_8CHANNEL   1
	#define	V_RUNCL_DOWNLOADANDSAVE_8CHANNEL_VOLUME   1

	#define	V_RUNCL_DOWNLOADANDSAVEVOLUME   2

	////////////////////////////////////// RUNCL_LOAD_IMAGE.CPP
	#define	V_RUNCL_LOADFRAME   1
	#define	V_RUNCL_CVT_COLOR_SPACE   1
	#define	V_RUNCL_IMG_VARIANCE   1
	#define	V_RUNCL_BLUR_IMAGE   1
	#define	V_RUNCL_MIPMAP_LINEAR   -1
	#define	V_RUNCL_IMG_GRADIENTS   -1

	#define	V_RUNCL_LOAD_GT_DEPTH   -1
	#define	V_RUNCL_CONVERT_DEPTH   -1
	#define	V_RUNCL_MIPMAP_DEPTHMAP   -2


	/////////////////////////////////////// RUNCL_MAPPING.CPP
	#define	V_RUNCL_COMPUTESIGMAS    1
	#define	V_RUNCL_UPDATEDEPTHCOSTVOL   -2
	#define	V_RUNCL_UPDATEDEPTHCOSTVOL_CDATABUF   false
	#define	V_RUNCL_UPDATEDEPTHCOSTVOL_CDATABUF_8CHAN   false
	#define	V_RUNCL_UPDATEDEPTHCOSTVOL_HDATABUF   false

	#define	V_RUNCL_UPDATEQD   -1
	#define	V_RUNCL_UPDATEG   -2
	#define	V_RUNCL_UPDATEA   -2
	#define	V_RUNCL_UPDATEA_DBG_DATABUF  -1
	//#define	V_RUNCL_COMPUTESIGMAS   -1
	#define	V_RUNCL_MEASUREDEPTHFIT   -2

	#define	V_RUNCL_SPATIALCOSTFNS   1
	#define	V_RUNCL_PARSIMONYCOSTFNS   1
	#define	V_RUNCL_EXHAUSTIVESEARCH   1

	/////////////////////////////////////// RUNCL_SETUP_KEYFRAME.CPP
	#define	V_RUNCL_ESTIMATECALIBRATION   1
	#define	V_RUNCL_TRANSFORM_DEPTHMAP   -2
	#define	V_RUNCL_SWAP_COSTVOL_POINTERS   -2
	#define	V_RUNCL_TRANSFORM_COSTVOLUME  -2
	#define	V_RUNCL_INITIALIZEDEPTHCOSTVOL   -2

	/////////////////////////////////////// RUNCL_TRACKING.CPP
	#define	V_RUNCL_PRECOM_PARAM_MAPS   1
	#define	V_RUNCL_UPDATE_TRACKING_DEPTHMAP  1
	#define	V_RUNCL_INITIALIZE_TRACKING_DEPTHMAP   1
	#define	V_RUNCL_SE3_RHO_SQ   1

	#define	V_RUNCL_ESTIMATESE3_LK   0
	#define	V_RUNCL_READ_RHO_SQ   0
	#define	V_RUNCL_READ_SE3_WEIGHTS   0
	#define	V_RUNCL_READ_SE3_INCR   0

	#define	V_RUNCL_TRACKING_RESULT   1
	#define	V_RELATIVEVEL_MAP   1
	#define	V_RUNCL_ATOMIC_TEST1   1
	#define	V_RUNCL_ATOMIC_TEST2   1




